live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/monokai_pro.toml"
]

[window]
opacity = 1.0

[scrolling]
history = 100000

[font]
size = 13.0

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = false
