live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/monokai_pro.toml"
]

[window]
opacity = 1.0
dimensions = { columns = 80, lines = 40 }

[scrolling]
history = 100000

[font]
size = 13.0
normal = { family = "MesloLGL Nerd Font Mono", style="Regular" }
bold = { style="Bold" }
italic = { style="Italic" }

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
	{key = "N", mods = "Control | Shift", action = "CreateNewWindow"},
	{key = "F", mods = "Control | Shift", action = "ToggleFullscreen"},
]
